import {
  PageDocument,
  PageDocumentSchema,
  DocumentMetadata,
  DocumentMetadataSchema,
  Node,
  NodeSchema,
  CURRENT_SCHEMA_VERSION,
  SCHEMA_NAME,
} from '@kubuild/schema';
import {
  validateDocument,
  validateDocumentSecurity,
  DocumentSecurityLimits,
} from '@kubuild/core';

export function extractJsonFromResponse(raw: string): unknown {
  let cleaned = raw.trim();
  // Strip Markdown code blocks if present (```json ... ``` or ``` ...)
  if (cleaned.startsWith('```')) {
    const firstNewline = cleaned.indexOf('\n');
    if (firstNewline !== -1) {
      cleaned = cleaned.slice(firstNewline + 1);
    }
    if (cleaned.endsWith('```')) {
      cleaned = cleaned.slice(0, cleaned.length - 3).trim();
    }
  }

  // Find the outermost JSON object bounds if there is extraneous text
  const firstBrace = cleaned.indexOf('{');
  const lastBrace = cleaned.lastIndexOf('}');
  if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
    cleaned = cleaned.slice(firstBrace, lastBrace + 1);
  }

  try {
    return JSON.parse(cleaned);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new Error(`Failed to parse AI response as JSON: ${msg}. Response was: ${raw.slice(0, 200)}...`);
  }
}

export function normalizeNodeTree(
  node: unknown,
  usedIds: Set<string> = new Set(),
  depth = 0,
): Node {
  if (!node || typeof node !== 'object') {
    throw new Error(`Invalid node at depth ${depth}: must be an object`);
  }

  const raw = node as Record<string, unknown>;
  const type = typeof raw.type === 'string' && raw.type.trim() ? raw.type.trim() : 'container';

  // Ensure deterministic, unique ID
  let id = typeof raw.id === 'string' && raw.id.trim() ? raw.id.trim() : '';
  if (!id || usedIds.has(id)) {
    let counter = 1;
    let candidate = `${type}-${counter}`;
    while (usedIds.has(candidate)) {
      counter++;
      candidate = `${type}-${counter}`;
    }
    id = candidate;
  }
  usedIds.add(id);

  // Normalize props
  const props =
    raw.props && typeof raw.props === 'object' && !Array.isArray(raw.props)
      ? (raw.props as Record<string, unknown>)
      : {};

  // Normalize styles
  const styles =
    raw.styles && typeof raw.styles === 'object' && !Array.isArray(raw.styles)
      ? (raw.styles as Node['styles'])
      : undefined;

  // Normalize children recursively
  let children: Node[] | undefined = undefined;
  if (Array.isArray(raw.children)) {
    children = raw.children
      .filter((c) => c && typeof c === 'object')
      .map((c) => normalizeNodeTree(c, usedIds, depth + 1));
  }

  return {
    id,
    type,
    props: Object.keys(props).length > 0 ? props : undefined,
    styles,
    children,
  };
}

export function normalizeAndValidatePageDocument(
  rawJson: unknown,
  securityLimits?: DocumentSecurityLimits,
): PageDocument {
  if (!rawJson || typeof rawJson !== 'object') {
    throw new Error('AI output must be a JSON object');
  }

  const obj = rawJson as Record<string, unknown>;

  // Case 1: AI returned directly a page node instead of PageDocument
  let docObject: Record<string, unknown>;
  if (obj.type === 'page' && !obj.document) {
    docObject = {
      schema: SCHEMA_NAME,
      version: CURRENT_SCHEMA_VERSION,
      metadata: {
        title: (typeof obj.props === 'object' && obj.props !== null && (obj.props as Record<string, unknown>).title) || 'AI Generated Page',
        description: 'Generated by KUBUILD AI',
      },
      document: obj,
    };
  } else {
    docObject = {
      schema: SCHEMA_NAME,
      version: typeof obj.version === 'string' ? obj.version : CURRENT_SCHEMA_VERSION,
      metadata: typeof obj.metadata === 'object' && obj.metadata !== null
        ? obj.metadata
        : { title: 'AI Generated Page', description: 'Generated by KUBUILD AI' },
      document: obj.document || obj,
    };
  }

  // Normalize the node tree and ensure IDs
  const usedIds = new Set<string>();
  const normalizedRoot = normalizeNodeTree(docObject.document, usedIds);

  if (normalizedRoot.type !== 'page') {
    normalizedRoot.type = 'page';
  }

  const parsedMetadata = DocumentMetadataSchema.parse({
    title: 'AI Generated Page',
    description: 'Generated by KUBUILD AI',
    author: 'KUBUILD AI',
    tags: ['ai-generated'],
    category: 'general',
    version: '1.0.0',
    ...(typeof docObject.metadata === 'object' && docObject.metadata !== null
      ? (docObject.metadata as Record<string, unknown>)
      : {}),
  });

  const finalDocument: PageDocument = {
    schema: SCHEMA_NAME,
    version: CURRENT_SCHEMA_VERSION,
    metadata: parsedMetadata,
    document: normalizedRoot as PageDocument['document'],
  };

  // 1. Zod Schema parse
  const parsed = PageDocumentSchema.safeParse(finalDocument);
  if (!parsed.success) {
    const issues = parsed.error.issues.map((i) => `${i.path.join('.')}: ${i.message}`).join('; ');
    throw new Error(`Document schema validation failed: ${issues}`);
  }

  // 2. Core document and security validation
  const validationResult = validateDocument(finalDocument, { securityLimits });
  if (!validationResult.valid) {
    const errorMsgs = validationResult.errors.map((e) => `${e.code}: ${e.message} (${e.path})`).join('; ');
    throw new Error(`Document validation failed: ${errorMsgs}`);
  }

  return parsed.data;
}

export function normalizeAndValidateSectionNode(
  rawJson: unknown,
  securityLimits?: DocumentSecurityLimits,
): Node {
  if (!rawJson || typeof rawJson !== 'object') {
    throw new Error('AI output must be a JSON object');
  }

  const usedIds = new Set<string>();
  const normalized = normalizeNodeTree(rawJson, usedIds);

  if (normalized.type !== 'section') {
    // If AI wrapped it or returned another root, enforce section
    normalized.type = 'section';
  }

  const parsed = NodeSchema.safeParse(normalized);
  if (!parsed.success) {
    const issues = parsed.error.issues.map((i) => `${i.path.join('.')}: ${i.message}`).join('; ');
    throw new Error(`Section node schema validation failed: ${issues}`);
  }

  // Security check
  const secCheck = validateDocumentSecurity({ document: normalized }, securityLimits);
  if (!secCheck.safe) {
    const issues = secCheck.errors.map((e) => `${e.code}: ${e.message}`).join('; ');
    throw new Error(`Section security check failed: ${issues}`);
  }

  return parsed.data;
}

export function normalizeAndValidateRefactoredNode(
  rawJson: unknown,
  originalNode: Node,
  securityLimits?: DocumentSecurityLimits,
): Node {
  if (!rawJson || typeof rawJson !== 'object') {
    throw new Error('AI output must be a JSON object');
  }

  const usedIds = new Set<string>();
  const normalized = normalizeNodeTree(rawJson, usedIds);

  // Preserve original ID and type if AI changed them accidentally
  normalized.id = originalNode.id;
  normalized.type = originalNode.type;

  const parsed = NodeSchema.safeParse(normalized);
  if (!parsed.success) {
    const issues = parsed.error.issues.map((i) => `${i.path.join('.')}: ${i.message}`).join('; ');
    throw new Error(`Refactored node schema validation failed: ${issues}`);
  }

  const secCheck = validateDocumentSecurity({ document: normalized }, securityLimits);
  if (!secCheck.safe) {
    const issues = secCheck.errors.map((e) => `${e.code}: ${e.message}`).join('; ');
    throw new Error(`Refactored node security check failed: ${issues}`);
  }

  return parsed.data;
}
