import { PageDocument, Node, DocumentMetadataSchema, DocumentMetadata, CURRENT_SCHEMA_VERSION } from '@kubuild/schema';
import type {
  KubuildAiEngineOptions,
  AiGeneratePageRequest,
  AiGenerateSectionRequest,
  AiRefactorNodeRequest,
  AiChatRequest,
  AiChatResponse,
  AiChatMessage,
  AiGenerateResponse,
  AiCompiledComponentSpec,
  AiStreamEvent,
  PagePlan,
  PlannedSection,
  AiPlanPageRequest,
  AiProviderGenerateResult,
} from '../types';
import {
  compileComponentCatalog,
  buildSystemPrompt,
  buildJsonSchemaForMode,
  appendClientInstructions,
  joinInstructions,
} from '../core/prompt-compiler';
import { getMessageText } from '../core/messages';
import {
  extractJsonFromResponse,
  normalizeAndValidatePageDocument,
  normalizeAndValidateSectionNode,
  normalizeAndValidateRefactoredNode,
} from '../core/normalizer';

type SectionCount = AiPlanPageRequest['sectionCount'];

/**
 * Shared section-count phrasing (e.g. "exactly 3 cohesive sections") used by BOTH the
 * planner prompt and the single-shot full-page prompt, so `sectionCount` means the same
 * thing no matter which generation path a request takes. `null` = no explicit count.
 */
function describeSectionCount(sectionCount: SectionCount): string | null {
  if (typeof sectionCount === 'number' && Number.isFinite(sectionCount) && sectionCount > 0) {
    return `exactly ${Math.floor(sectionCount)} cohesive sections`;
  }
  if (sectionCount && typeof sectionCount === 'object' && (sectionCount.min || sectionCount.max)) {
    const min = sectionCount.min ?? 3;
    const max = sectionCount.max ?? 8;
    return `between ${min} and ${max} cohesive sections`;
  }
  return null;
}

/** True when a plan has at least one section to generate. */
function hasPlannedSections(
  plan: PagePlan | null | undefined,
): plan is PagePlan & { sections: PlannedSection[] } {
  return !!plan && Array.isArray(plan.sections) && plan.sections.length > 0;
}

/**
 * Generic plan substituted when the model's plan JSON cannot be parsed. Shared by
 * `planPage` and `streamPage`; marked `usedFallback` so hosts can tell the user.
 */
function buildFallbackPlan(prompt: string): PagePlan & { sections: PlannedSection[] } {
  return {
    title: 'AI Generated Page',
    description: 'Generated by KUBUILD AI',
    sections: [
      { type: 'hero', title: 'Hero Banner', prompt: `Hero section for: ${prompt}` },
      { type: 'features', title: 'Key Features', prompt: `Features grid for: ${prompt}` },
      {
        type: 'testimonials',
        title: 'Testimonials',
        prompt: `Social proof and customer reviews for: ${prompt}`,
      },
      { type: 'cta', title: 'Call To Action', prompt: `Call to action section for: ${prompt}` },
      { type: 'footer', title: 'Footer', prompt: `Footer navigation and copyright for: ${prompt}` },
    ],
    usedFallback: true,
  };
}

const PLAN_FALLBACK_MESSAGE =
  'The AI response could not be parsed as a page plan, so a generic default plan was used instead.';

export class KubuildAiEngine {
  private options: KubuildAiEngineOptions;
  private catalog: AiCompiledComponentSpec[];

  constructor(options: KubuildAiEngineOptions) {
    if (!options.adapter) {
      throw new Error('KubuildAiEngine requires an adapter instance');
    }
    this.options = options;
    this.catalog = compileComponentCatalog(options.registry);
  }

  get adapterName(): string {
    return this.options.adapter.name;
  }

  refreshCatalog(): void {
    this.catalog = compileComponentCatalog(this.options.registry);
  }

  private log(level: 'info' | 'warn' | 'error' | 'debug', message: string, meta?: unknown): void {
    if (this.options.logger) {
      this.options.logger(level, message, meta);
    } else if (this.options.debug) {
      const ts = new Date().toISOString();
      console.log(`[KUBUILD-AI ${level.toUpperCase()}] [${ts}] ${message}`, meta !== undefined ? meta : '');
    }
  }

  async generatePage(
    request: AiGeneratePageRequest,
    context?: { signal?: AbortSignal },
  ): Promise<AiGenerateResponse<PageDocument>> {
    // An approved plan is honoured exactly like `streamPage` honours it: each planned
    // section is generated in turn, instead of a single-shot prompt silently ignoring it.
    if (hasPlannedSections(request.plan)) {
      return this.generatePageFromPlan(request, context);
    }

    let rawText = '';
    try {
      this.log('info', `Generating full page for prompt: "${request.prompt}"`);
      const systemPrompt = appendClientInstructions(
        buildSystemPrompt({
          catalog: this.catalog,
          mode: 'full-page',
          prefix: this.options.systemPromptPrefix,
          stylePreference: request.stylePreference,
        }),
        request.instructions,
      );

      let userPrompt = `User Request: ${request.prompt}`;
      if (request.tone) userPrompt += `\nTone: ${request.tone}`;
      if (request.locale) userPrompt += `\nLanguage/Locale: ${request.locale}`;
      const sectionCountPhrase = describeSectionCount(request.sectionCount);
      if (sectionCountPhrase) {
        userPrompt += `\nSection Count: the page root must contain ${sectionCountPhrase} as its direct children.`;
      }
      if (request.conversationHistory && request.conversationHistory.length > 0) {
        const chatContext = request.conversationHistory
          .map((m) => `${m.role.toUpperCase()}: ${getMessageText(m)}`)
          .join('\n');
        userPrompt += `\n\nPrior Conversation Discussion Context:\n${chatContext}`;
      }

      const jsonSchema = buildJsonSchemaForMode('full-page');

      const result = await this.options.adapter.generate({
        systemPrompt,
        userPrompt,
        jsonSchema,
        signal: context?.signal,
      });

      this.log('debug', 'Raw model response (generatePage)', result.text);

      rawText = result.text;
      const rawJson = extractJsonFromResponse(rawText);
      const document = normalizeAndValidatePageDocument(
        rawJson,
        this.options.securityLimits,
      );

      // Merge user requested metadata if given
      if (request.metadata) {
        document.metadata = DocumentMetadataSchema.parse({
          ...document.metadata,
          ...request.metadata,
        });
      }

      this.log(
        'info',
        `Full page successfully generated: "${document.metadata?.title || 'Untitled'}" (${document.document.children?.length || 0} sections)`,
      );

      return {
        success: true,
        data: document,
        usage: result.usage,
        rawModelResponse: rawText,
      };
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      this.log('error', `Generation failed: ${message}`);
      return {
        success: false,
        error: {
          code: 'GENERATION_ERROR',
          message,
        },
        rawModelResponse: rawText || undefined,
      };
    }
  }

  /**
   * Non-streaming counterpart of `streamPage` for a pre-approved plan: drains the same
   * progressive pipeline and returns the assembled document, so both paths produce the
   * same sections for the same plan.
   */
  private async generatePageFromPlan(
    request: AiGeneratePageRequest,
    context?: { signal?: AbortSignal },
  ): Promise<AiGenerateResponse<PageDocument>> {
    let document: PageDocument | null = null;
    let error: { code: string; message: string } | null = null;

    for await (const event of this.streamPage(request, context)) {
      if (event.type === 'complete') document = event.document;
      if (event.type === 'error') error = event.error;
    }

    if (document) {
      return { success: true, data: document };
    }
    return {
      success: false,
      error: {
        code: 'GENERATION_ERROR',
        message: error?.message ?? 'Page generation from the approved plan produced no document.',
        details: error ? { streamCode: error.code } : undefined,
      },
    };
  }

  async generateSection(
    request: AiGenerateSectionRequest,
    context?: { signal?: AbortSignal },
  ): Promise<AiGenerateResponse<Node>> {
    let rawText = '';
    try {
      const systemPrompt = appendClientInstructions(
        buildSystemPrompt({
          catalog: this.catalog,
          mode: 'section',
          prefix: this.options.systemPromptPrefix,
          stylePreference: request.stylePreference,
        }),
        request.instructions,
      );

      let userPrompt = `Generate a single section node for: ${request.prompt}`;
      if (request.targetSectionType) {
        userPrompt += `\nTarget Section Purpose: ${request.targetSectionType}`;
      }
      if (request.parentContext) {
        userPrompt += `\nSurrounding Page Context: ${request.parentContext}`;
      }

      const jsonSchema = buildJsonSchemaForMode('section');

      const result = await this.options.adapter.generate({
        systemPrompt,
        userPrompt,
        jsonSchema,
        signal: context?.signal,
      });

      this.log('debug', 'Raw model response (generateSection)', result.text);

      rawText = result.text;
      const rawJson = extractJsonFromResponse(rawText);
      const sectionNode = normalizeAndValidateSectionNode(
        rawJson,
        this.options.securityLimits,
      );

      return {
        success: true,
        data: sectionNode,
        usage: result.usage,
        rawModelResponse: rawText,
      };
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        success: false,
        error: {
          code: 'SECTION_GENERATION_ERROR',
          message,
        },
        rawModelResponse: rawText || undefined,
      };
    }
  }

  async refactorNode(
    request: AiRefactorNodeRequest,
    context?: { signal?: AbortSignal },
  ): Promise<AiGenerateResponse<Node>> {
    let rawText = '';
    try {
      const systemPrompt = appendClientInstructions(
        buildSystemPrompt({
          catalog: this.catalog,
          mode: 'refactor',
          prefix: this.options.systemPromptPrefix,
          stylePreference: request.stylePreference,
        }),
        request.instructions,
      );

      const userPrompt = `Instruction: ${request.instruction}\n\nCurrent Node:\n${JSON.stringify(request.node, null, 2)}`;
      const jsonSchema = buildJsonSchemaForMode('refactor');

      const result = await this.options.adapter.generate({
        systemPrompt,
        userPrompt,
        jsonSchema,
        signal: context?.signal,
      });

      rawText = result.text;
      const rawJson = extractJsonFromResponse(rawText);
      const updatedNode = normalizeAndValidateRefactoredNode(
        rawJson,
        request.node,
        this.options.securityLimits,
      );

      return {
        success: true,
        data: updatedNode,
        usage: result.usage,
        rawModelResponse: rawText,
      };
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        success: false,
        error: {
          code: 'REFACTOR_ERROR',
          message,
        },
        rawModelResponse: rawText || undefined,
      };
    }
  }

  private buildPlanPrompts(request: AiPlanPageRequest): { systemPrompt: string; userPrompt: string } {
    const sectionCountPhrase = describeSectionCount(request.sectionCount);
    const sectionGuidance = sectionCountPhrase
      ? `Plan ${sectionCountPhrase} that fulfill the request.`
      : 'Plan between 4 to 6 cohesive, essential sections (e.g., hero, features, testimonials, pricing, cta, footer) that fulfill the request thoroughly. If the user request mentions a specific number or list of sections, respect the user request.';

    const planSystemPrompt = `
You are a web architect for the KUBUILD page builder.
Given the user's prompt, plan the website structure. Output pure JSON (no markdown fences, no explanatory text):
{
  "title": "<Page Title>",
  "description": "<Page Description>",
  "pageStyles": {
    "base": {
      "backgroundColor": "#ffffff",
      "fontFamily": "Inter, system-ui, sans-serif",
      "color": "#111827",
      "minHeight": "100vh"
    }
  },
  "sections": [
    {
      "type": "<hero|features|pricing|testimonials|cta|contact|footer>",
      "title": "<Brief title>",
      "prompt": "<Detailed prompt for generating this specific section with components, layout, and content>"
    }
  ]
}
${sectionGuidance}
`;

    let planUserPrompt = `User Request: ${request.prompt}`;
    if (request.stylePreference) {
      planUserPrompt += `\nStyle Preference: ${request.stylePreference}`;
    }
    if (request.tone) planUserPrompt += `\nTone: ${request.tone}`;
    if (request.locale) planUserPrompt += `\nLocale: ${request.locale}`;
    if (request.conversationHistory && request.conversationHistory.length > 0) {
      const chatContext = request.conversationHistory
        .map((m) => `${m.role.toUpperCase()}: ${getMessageText(m)}`)
        .join('\n');
      planUserPrompt += `\n\nPrior Conversation Discussion Context:\n${chatContext}`;
    }

    return {
      systemPrompt: appendClientInstructions(planSystemPrompt, request.instructions),
      userPrompt: planUserPrompt,
    };
  }

  async planPage(
    request: AiPlanPageRequest,
    context?: { signal?: AbortSignal },
  ): Promise<AiGenerateResponse<PagePlan>> {
    const { systemPrompt, userPrompt } = this.buildPlanPrompts(request);
    this.log('info', `Planning website layout for: "${request.prompt}"`);

    let planResult: AiProviderGenerateResult;
    try {
      planResult = await this.options.adapter.generate({
        systemPrompt,
        userPrompt,
        signal: context?.signal,
      });
    } catch (err: unknown) {
      // A provider failure (auth, rate limit, abort, network) is a real error. Only an
      // unparseable plan falls back to the default plan, matching `streamPage`.
      const message = err instanceof Error ? err.message : String(err);
      this.log('error', `Planning failed: ${message}`);
      return {
        success: false,
        error: { code: 'PLAN_ERROR', message },
      };
    }

    const rawText = planResult.text;
    let plan: PagePlan | null = null;
    let parseError = '';
    try {
      const parsed = extractJsonFromResponse(rawText) as PagePlan;
      if (hasPlannedSections(parsed)) {
        plan = parsed;
      } else {
        parseError = 'Plan JSON has no non-empty "sections" array';
      }
    } catch (err: unknown) {
      parseError = err instanceof Error ? err.message : String(err);
    }

    if (plan) {
      return {
        success: true,
        data: plan,
        usage: planResult.usage,
        rawModelResponse: rawText,
      };
    }

    this.log('warn', 'Failed to parse plan JSON, using fallback plan', parseError);
    return {
      success: true,
      data: buildFallbackPlan(request.prompt),
      usedFallback: true,
      warnings: [{ code: 'PLAN_FALLBACK', message: PLAN_FALLBACK_MESSAGE, details: parseError }],
      usage: planResult.usage,
      rawModelResponse: rawText || undefined,
    };
  }

  /**
   * Progressive Section Streaming Generator.
   * Emits structured SSE events: status -> metadata -> section (one by one) -> complete.
   */
  async *streamPage(
    request: AiGeneratePageRequest,
    context?: { signal?: AbortSignal },
  ): AsyncIterable<AiStreamEvent> {
    try {
      this.log('info', `[SSE] Starting streamPage for prompt: "${request.prompt}"`);

      yield {
        type: 'status',
        message: 'Analyzing requirements and planning page sections...',
      };

      let plan: PagePlan;

      if (hasPlannedSections(request.plan)) {
        plan = request.plan;
        this.log('info', `[SSE] Using approved pre-planned structure with ${plan.sections?.length ?? 0} sections`);
      } else {
        // 1. Plan page sections
        const { systemPrompt: planSystemPrompt, userPrompt: planUserPrompt } = this.buildPlanPrompts(request);

        this.log('info', '[SSE] Generating website layout plan...');
        const planResult = await this.options.adapter.generate({
          systemPrompt: planSystemPrompt,
          userPrompt: planUserPrompt,
          signal: context?.signal,
        });

        this.log('debug', '[SSE] Raw plan response from model', planResult.text);

        let parsedPlan: PagePlan | null = null;
        try {
          parsedPlan = extractJsonFromResponse(planResult.text) as PagePlan;
          this.log('debug', '[SSE] Parsed plan successfully', parsedPlan);
        } catch (parseErr) {
          this.log('warn', '[SSE] Failed to parse plan JSON, using fallback plan', parseErr);
        }

        if (hasPlannedSections(parsedPlan)) {
          plan = parsedPlan;
        } else {
          plan = buildFallbackPlan(request.prompt);
          yield { type: 'status', message: PLAN_FALLBACK_MESSAGE };
        }
      }

      const sectionsToGenerate = hasPlannedSections(plan)
        ? plan.sections
        : buildFallbackPlan(request.prompt).sections;

      const metadata: DocumentMetadata = DocumentMetadataSchema.parse({
        title: plan.title || 'AI Generated Page',
        description: plan.description || 'Generated by KUBUILD AI',
        author: 'KUBUILD AI',
        tags: ['ai-generated', 'progressive-stream'],
        category: 'landing',
        version: '1.0.0',
        ...(request.metadata || {}),
      });

      const rootPageNode: Node = {
        id: 'root-page',
        type: 'page',
        styles: plan.pageStyles || {
          base: {
            backgroundColor: '#ffffff',
            fontFamily: 'Inter, system-ui, sans-serif',
            color: '#111827',
            minHeight: '100vh',
          },
        },
        children: [],
      };

      // 2. Emit initial metadata so canvas can render initial empty page immediately!
      this.log('info', `[SSE] Emitting metadata: "${metadata.title}"`);
      yield {
        type: 'metadata',
        metadata,
        rootPageNode,
      };

      this.log(
        'info',
        `[SSE] Plan ready with ${sectionsToGenerate.length} sections: ${sectionsToGenerate.map((s) => s.title).join(', ')}`,
      );
      yield {
        type: 'status',
        message: `Plan ready with ${sectionsToGenerate.length} sections: ${sectionsToGenerate.map((s) => s.title).join(', ')}`,
      };

      // 3. Sequentially generate each section and stream it!
      const completedSections: Node[] = [];
      const total = sectionsToGenerate.length;

      for (let i = 0; i < total; i++) {
        if (context?.signal?.aborted) {
          this.log('warn', '[SSE] Streaming aborted by client signal');
          throw new Error('Streaming aborted by client');
        }

        const plannedSec = sectionsToGenerate[i];
        this.log(
          'info',
          `[SSE] Generating section ${i + 1}/${total} [${plannedSec.type}]: "${plannedSec.title}"`,
        );
        yield {
          type: 'status',
          message: `Generating section ${i + 1}/${total} (${plannedSec.title})...`,
        };

        const secRes = await this.generateSection(
          {
            prompt: plannedSec.prompt,
            stylePreference: request.stylePreference,
            instructions: request.instructions,
            targetSectionType: plannedSec.type,
            parentContext: `Website: ${plan.title}. Previous sections: ${sectionsToGenerate.slice(0, i).map((s) => s.title).join(', ')}`,
          },
          { signal: context?.signal },
        );

        if (secRes.success && secRes.data) {
          this.log(
            'info',
            `[SSE] Section ${i + 1}/${total} generated successfully: [${secRes.data.id || secRes.data.type}]`,
          );
          completedSections.push(secRes.data);
          yield {
            type: 'section',
            index: i,
            total,
            section: secRes.data,
          };
        } else {
          this.log('error', `[SSE] Section ${i + 1}/${total} failed`, secRes.error?.message);
        }
      }

      if (completedSections.length === 0) {
        this.log('error', '[SSE] All sections failed to generate.');
        yield {
          type: 'error',
          error: {
            code: 'STREAM_GENERATION_FAILED',
            message: 'All sections failed to generate. Please check server logs or retry.',
          },
        };
        return;
      }

      // 4. Assemble final document and emit complete event
      const finalDocument: PageDocument = {
        schema: 'stora.page',
        version: CURRENT_SCHEMA_VERSION,
        metadata,
        document: {
          ...rootPageNode,
          children: completedSections,
        } as PageDocument['document'],
      };

      this.log(
        'info',
        `[SSE] All ${completedSections.length} sections generated. Emitting complete event.`,
      );
      yield {
        type: 'complete',
        document: finalDocument,
      };
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      this.log('error', `[SSE] Streaming failed: ${message}`);
      yield {
        type: 'error',
        error: {
          code: 'STREAM_ERROR',
          message,
        },
      };
    }
  }

  /**
   * Builds the system/user prompt pair shared by `chat()` and `chatStream()` — the exact
   * same document/selection grounding is used regardless of whether the response is
   * streamed token-by-token or returned as a single request/response (STORA-515).
   */
  private buildChatPrompt(request: AiChatRequest): { systemPrompt: string; userPrompt: string } {
    let systemPrompt = `You are the KUBUILD AI Assistant — an expert web designer, developer, and page architecture consultant.
Your role is to assist users with creating, designing, refining, and understanding web pages built with the KUBUILD builder.
Answer questions directly, concisely, and helpfully using friendly professional tone and markdown formatting.

### Available KUBUILD Components:
${this.catalog.map((c) => `- **${c.type}** (${c.category}): ${c.label}${c.description ? ` — ${c.description}` : ''}`).join('\n')}
`;

    if (this.options.systemPromptPrefix) {
      systemPrompt = `${this.options.systemPromptPrefix}\n\n${systemPrompt}`;
    }

    if (request.currentDocument) {
      const doc = request.currentDocument;
      const sections = doc.document?.children || [];
      const sectionSummary = sections
        .map((s, idx) => `Section ${idx + 1}: id="${s.id}", type="${s.type}", title="${(s.props?.title as string) || 'untitled'}", childrenCount=${s.children?.length || 0}`)
        .join('\n');

      systemPrompt += `\n### Current Page in Builder Canvas:
- Title: ${doc.metadata?.title || 'Untitled Page'}
- Description: ${doc.metadata?.description || 'N/A'}
- Total Sections: ${sections.length}
- Sections Summary:
${sectionSummary || '(Canvas is currently empty)'}
`;
    }

    if (request.selectedNodeId) {
      systemPrompt += `\nCurrently Selected Component Node ID: "${request.selectedNodeId}"`;
    }

    // Host/user instructions always go last, after every built-in rule and context block.
    systemPrompt = appendClientInstructions(
      systemPrompt,
      joinInstructions(request.instructions, request.systemPrompt),
    );

    // Extract last user message
    const lastUserMsg = [...request.messages].reverse().find((m) => m.role === 'user');
    const userPrompt = lastUserMsg ? getMessageText(lastUserMsg) || 'Hello' : 'Hello';

    return { systemPrompt, userPrompt };
  }

  /**
   * Conversational Assistant / Q&A.
   * Can discuss web design, explain KUBUILD components, review current page,
   * suggest improvements, or recommend copywriting.
   *
   * Single request/response — unchanged since before STORA-515. See `chatStream()` for
   * the token-level streaming variant.
   */
  async chat(
    request: AiChatRequest,
    context?: { signal?: AbortSignal },
  ): Promise<AiGenerateResponse<AiChatResponse>> {
    let rawText = '';
    try {
      if (!request.messages || !Array.isArray(request.messages) || request.messages.length === 0) {
        return {
          success: false,
          error: {
            code: 'INVALID_CHAT_REQUEST',
            message: '"messages" array is required and must not be empty',
          },
        };
      }

      this.log('info', `Processing chat turn with ${request.messages.length} messages`);

      const { systemPrompt, userPrompt } = this.buildChatPrompt(request);

      const result = await this.options.adapter.generate({
        systemPrompt,
        userPrompt,
        messages: request.messages,
        signal: context?.signal,
      });

      rawText = result.text.trim();

      const assistantMessage: AiChatMessage = {
        role: 'assistant',
        content: rawText,
        timestamp: Date.now(),
      };

      return {
        success: true,
        data: {
          message: assistantMessage,
        },
        usage: result.usage,
        rawModelResponse: rawText,
      };
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      this.log('error', `Chat failed: ${message}`);
      return {
        success: false,
        error: {
          code: 'CHAT_ERROR',
          message,
        },
        rawModelResponse: rawText || undefined,
      };
    }
  }

  /**
   * Token-level streaming variant of `chat()` (STORA-515). Emits `chat-chunk` events as
   * partial text arrives, then a terminal `chat-complete` event with the fully assembled
   * assistant message — the same `AsyncIterable<AiStreamEvent>` mechanism `streamPage`
   * already uses, so it can be piped over SSE by `createAiHandler`/consumed by
   * `KubuildAiClient` with no separate transport.
   *
   * When the configured adapter does not implement `generateStream` (e.g. the generic
   * custom/HTTP adapter), this falls back to a single non-streaming `generate()` call and
   * emits the entire response as one `chat-chunk`, so callers never see an error just
   * because the underlying provider can't stream — only a less granular update cadence.
   */
  async *chatStream(
    request: AiChatRequest,
    context?: { signal?: AbortSignal },
  ): AsyncIterable<AiStreamEvent> {
    try {
      if (!request.messages || !Array.isArray(request.messages) || request.messages.length === 0) {
        yield {
          type: 'error',
          error: {
            code: 'INVALID_CHAT_REQUEST',
            message: '"messages" array is required and must not be empty',
          },
        };
        return;
      }

      this.log(
        'info',
        `[SSE] Starting chatStream with ${request.messages.length} messages (adapter: ${this.options.adapter.name})`,
      );

      const { systemPrompt, userPrompt } = this.buildChatPrompt(request);

      let accumulated = '';
      let usage: AiGenerateResponse<AiChatResponse>['usage'];

      if (typeof this.options.adapter.generateStream === 'function') {
        const generator = this.options.adapter.generateStream({
          systemPrompt,
          userPrompt,
          messages: request.messages,
          signal: context?.signal,
        });

        while (true) {
          const { value, done } = await generator.next();
          if (done) {
            usage = value?.usage;
            break;
          }
          accumulated += value;
          yield { type: 'chat-chunk', delta: value, content: accumulated };
        }
      } else {
        this.log(
          'debug',
          `Adapter "${this.options.adapter.name}" has no generateStream; falling back to non-streaming chat`,
        );
        const result = await this.options.adapter.generate({
          systemPrompt,
          userPrompt,
          messages: request.messages,
          signal: context?.signal,
        });
        accumulated = result.text;
        usage = result.usage;
        yield { type: 'chat-chunk', delta: accumulated, content: accumulated };
      }

      const assistantMessage: AiChatMessage = {
        role: 'assistant',
        content: accumulated.trim(),
        timestamp: Date.now(),
      };

      this.log('info', '[SSE] Chat stream completed', usage);
      yield { type: 'chat-complete', message: assistantMessage };
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      this.log('error', `[SSE] Chat streaming failed: ${message}`);
      yield {
        type: 'error',
        error: {
          code: 'CHAT_STREAM_ERROR',
          message,
        },
      };
    }
  }
}
